# Generated by Django 3.2.7 on 2021-11-02 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app2005050209', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iphon', models.CharField(max_length=12, unique=True, verbose_name='手机号码')),
                ('sex', models.CharField(max_length=20, verbose_name='性别')),
                ('occupation', models.CharField(blank=True, max_length=20, verbose_name='职业')),
                ('birthday', models.DateField(blank=True, max_length=20, verbose_name='生日')),
                ('education', models.CharField(blank=True, max_length=20, verbose_name='教育程度')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
